name: 'Easy Coding Standard for Shopware 6'
description: 'Easy Coding Standard for Shopware 6'
author: 'pietrzakadrian'

branding:
  icon: 'check'
  color: 'blue'

inputs:
  directory:
    description: 'directory to check'
    required: true
  config:
    description: 'config file path'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.config }}