name: 'Easy Coding Standard GitHub Action'
description: 'Easy Coding Standard GitHub Action'
author: 'pietrzakadrian'

branding:
  icon: 'check'
  color: 'blue'

inputs:
  directories:
    description: 'directories to check'
    required: true
  config:
    description: 'config file path'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directories }}
    - ${{ inputs.config }}